### PR TITLE
Allows for optional password in details (edit) page

### PR DESCRIPTION
**Pull request by DanielSBrown**
Getting this up as a quick fix. I want to try to extract the javascript function out into a separate file instead of there being duplicate code between `details.html.erb` and `new.html.erb`

### CODE REVIEW

**Comment by efatsi** [comment]
Looks like you might have missed something:

Screen Shot 2020-05-07 at 11 42 12 AM

**Comment by DanielSBrown** [comment]
Hmm it would be nice to add the partial to the repo, wouldn't it? I just did `git add -p` and forgot to manually add new files

**Comment by DanielSBrown** [comment]
I've got some time to work on this today -- could I add that (and the title validation) in this PR or should I make a new one?

**Comment by DanielSBrown** [comment]
@efatsi I added the most recent commit to make it so that if you're the owner/have edit privileges, you don't have to remember the password to access the story. I was finding that I had forgotten the passwords to all of the stories I wrote, and it didn't feel good to be locked out

**Pull request closed without merging**
