### PR TITLE
[#136] Add handlebars templating to story descriptions

### PR DESCRIPTION
**Pull request by noahko96**
This allows users to include additional templating in their scene content. Several new options include if statements in which you can conditionally show text based on the existence of an item or a stat being greater than, less than, etc. than a certain value. You can still show the value of a stat and do all of the math problems that you used to be able to do as well. Also, the templating was added to the tutorial.

basic_templating
templating_conditionals
templating_math

### CODE REVIEW

**Review by efatsi — APPROVED** [review]
awesome stuff. Any thoughts on the UX behind the instructions available? I see you've updated the tutorials, do you think it would be worth it to have any other instructions?

**Comment by noahko96** [comment]
I was a little worried that people without a coding background would have trouble understanding my instructions that I added to the tutorial, but I also did not want to turn the tutorial into a mostly templating based tutorial and three pages already seemed like a lot to me, but I am open to any suggestions you would have to make the instructions more clear for users.

**Comment by efatsi** [comment]
Yeah, I think the tutorial is at capacity. I think if we wanted to explain the options more, a good move would be having a one-pager help document that was linked to from a "Formatting Help" link or something near the scene editor. That could open up in a new tab, or we could repurpose the modal functionality, but that might be a bit of trouble for not that much benefit.

**Comment by noahko96** [comment]
I think that could work. If I were to do that, I would probably drop the two Bonus Templating pages from the tutorial and also link to this Formatting Help page from that initial Using Templating tutorial page to keep the tutorial itself simple. That would be in addition to putting a Formatting Help link somewhere near the content section of the scene editor.

**Comment by efatsi** [comment]
That sounds like a great plan.

**Review by efatsi — APPROVED** [review]
Awesome stuff man. Impressive detail on the help page. I think that's going to really open up this feature for folks.

**Pull request merged**
